### ISSUE TITLE
simplify path to image files

### ISSUE THREAD

**Issue by mtmorgan** [lpantano/dummychapter1#1]
https://github.com/lpantano/dummychapter1/blob/9e59faaa8620bc2863db6897f791f89638123ec4/vignettes/dummychapter1.Rmd#L141 `file.path()` is not needed, just add more path to `system.file()`, e.g., `system.file(package='dummychapter1', 'vignettes', 'fig.png')`

**Comment by lpantano** [comment]
you are totally right. Done!
